"""participant_values

Revision ID: 002
Revises: 001
Create Date: 2025-12-13 10:59:54.432889

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "002"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "TEXT",
        "PHONE",
        "TEXTAREA",
        "LINK",
        "CHECKBOX",
        "USER",
        "DURATION",
        "IMAGE",
        "SELECT",
        "NUM",
        "FILE",
        name="valuetype",
    ).create(op.get_bind())
    op.create_table(
        "participant_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "TEXT",
                "PHONE",
                "TEXTAREA",
                "LINK",
                "CHECKBOX",
                "USER",
                "DURATION",
                "IMAGE",
                "SELECT",
                "NUM",
                "FILE",
                name="valuetype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
            name=op.f("fk_participant_values_participant_id_participants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participant_values")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("participant_values")
    sa.Enum(
        "TEXT",
        "PHONE",
        "TEXTAREA",
        "LINK",
        "CHECKBOX",
        "USER",
        "DURATION",
        "IMAGE",
        "SELECT",
        "NUM",
        "FILE",
        name="valuetype",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
