"""ticket_external_id

Revision ID: 003
Revises: 002
Create Date: 2025-12-28 10:42:28.677012

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "003"
down_revision = "002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("external_id", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_tickets_external_id"), "tickets", ["external_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickets_external_id"), table_name="tickets")
    op.drop_column("tickets", "external_id")
    # ### end Alembic commands ###
