"""simplify_schedule

Revision ID: 004
Revises: 003
Create Date: 2026-01-17 15:04:13.791254

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "004"
down_revision = "003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blocks")
    op.add_column(
        "schedule", sa.Column("nomination_title", sa.String(), nullable=False)
    )
    op.add_column("schedule", sa.Column("block_title", sa.String(), nullable=False))
    op.drop_constraint(
        op.f("fk_schedule_participant_id_participants"), "schedule", type_="foreignkey"
    )
    op.drop_column("schedule", "participant_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule",
        sa.Column("participant_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_schedule_participant_id_participants"),
        "schedule",
        "participants",
        ["participant_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("schedule", "block_title")
    op.drop_column("schedule", "nomination_title")
    op.create_table(
        "blocks",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "start_order",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blocks")),
        sa.UniqueConstraint(
            "start_order",
            name=op.f("uq_blocks_start_order"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
