"""fix_values_cascade

Revision ID: 006
Revises: 005
Create Date: 2026-01-19 21:13:04.267498

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "006"
down_revision = "005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_participant_values_participant_id_participants"),
        "participant_values",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_participant_values_participant_id_participants"),
        "participant_values",
        "participants",
        ["participant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_participant_values_participant_id_participants"),
        "participant_values",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_participant_values_participant_id_participants"),
        "participant_values",
        "participants",
        ["participant_id"],
        ["id"],
    )
    # ### end Alembic commands ###
