"""achievement_secret_id_necessary

Revision ID: 006
Revises: 005
Create Date: 2024-12-28 17:05:11.280936

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "006"
down_revision = "005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "achievements", "secret_id", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "achievements", "secret_id", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
