"""schedule_break_support

Revision ID: 007
Revises: 006
Create Date: 2026-01-19 22:36:32.601608

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "007"
down_revision = "006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schedule", "nomination_title", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "schedule", "block_title", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schedule", "block_title", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "schedule", "nomination_title", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
