"""remove_quest_registration

Revision ID: 007
Revises: 006
Create Date: 2025-01-02 17:42:16.835414

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "007"
down_revision = "006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quest_registrations")
    op.drop_column("settings", "quest_registrations_limit")
    op.drop_column("settings", "quest_registration_enabled")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column(
            "quest_registration_enabled",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "settings",
        sa.Column(
            "quest_registrations_limit",
            sa.INTEGER(),
            server_default=sa.text("10"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_table(
        "quest_registrations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_quest_registrations_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_quest_registrations"),
        sa.UniqueConstraint("user_id", name="uq_quest_registrations_user_id"),
    )
    # ### end Alembic commands ###
