"""codes

Revision ID: 009
Revises: 008
Create Date: 2025-04-12 13:46:06.774151

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "009"
down_revision = "008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "codes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("achievement_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("ticket_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievements.id"],
            name=op.f("fk_codes_achievement_id_achievements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_codes_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_codes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_codes")),
        sa.UniqueConstraint("achievement_id", name=op.f("uq_codes_achievement_id")),
        sa.UniqueConstraint("ticket_id", name=op.f("uq_codes_ticket_id")),
        sa.UniqueConstraint("user_id", name=op.f("uq_codes_user_id")),
    )
    op.drop_constraint("uq_achievements_secret_id", "achievements", type_="unique")
    op.drop_column("achievements", "secret_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "achievements",
        sa.Column("secret_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        "uq_achievements_secret_id", "achievements", ["secret_id"]
    )
    op.drop_table("codes")
    # ### end Alembic commands ###
