"""refactor

Revision ID: 013
Revises: 012
Create Date: 2025-05-03 15:11:06.819493

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "013"
down_revision = "012"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("contest_entries", "flags")
    op.alter_column("flags", "contest_name", new_column_name="flag_name")
    op.drop_constraint("uq_codes_achievement_id", "codes", type_="unique")
    op.drop_constraint("uq_codes_ticket_id", "codes", type_="unique")
    op.drop_constraint("uq_codes_user_id", "codes", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_codes_user_id", "codes", ["user_id"])
    op.create_unique_constraint("uq_codes_ticket_id", "codes", ["ticket_id"])
    op.create_unique_constraint("uq_codes_achievement_id", "codes", ["achievement_id"])
    op.rename_table("flags", "contest_entries")
    op.alter_column("contest_entries", "flag_name", new_column_name="contest_name")
    # ### end Alembic commands ###
