"""schedule_event_public_ids

Revision ID: 015
Revises: 014
Create Date: 2025-05-14 20:37:16.589931

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "015"
down_revision = "014"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "blocks",
        "start_order",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.add_column(
        "schedule",
        sa.Column("public_id", sa.Integer(), autoincrement=True, nullable=False),
    )
    op.create_unique_constraint(
        op.f("uq_schedule_public_id"), "schedule", ["public_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_schedule_public_id"), "schedule", type_="unique")
    op.drop_column("schedule", "public_id")
    op.alter_column(
        "blocks",
        "start_order",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
