version: '3.7'
services:
  bot:
    container_name: 'fanfan-bot'
    build:
      context: .
      dockerfile: buildfiles/Dockerfile
    env_file:
      - .env
    restart: always
    stop_signal: SIGINT
    depends_on:
      - db
      - redis
  db:
    container_name: 'fanfan-db'
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "54320:5432"
  redis:
    container_name: 'fanfan-redis'
    build:
      context: buildfiles
      dockerfile: RedisDockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6378:6378"

volumes:
  db-data:
    name: "fanfan-db-data"
    driver: local
  redis-data:
    name: "fanfan-redis-data"
    driver: local
