version: '3.8'
services:
  bot:
    container_name: 'fanfan-bot'
    build:
      context: .
      dockerfile: buildfiles/BotDockerfile
    env_file:
      - .docker-env
    restart: always
    stop_signal: SIGINT
    volumes:
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
      - redis
  panel:
    container_name: 'fanfan-panel'
    build:
      context: .
      dockerfile: buildfiles/PanelDockerfile
    env_file:
      - .docker-env
    restart: always
    stop_signal: SIGINT
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - db
  db:
    container_name: 'fanfan-db'
    build:
      context: buildfiles
      dockerfile: DBDockerfile
    restart: always
    env_file:
      - .docker-env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "54320:5432"
  redis:
    container_name: 'fanfan-redis'
    build:
      context: buildfiles
      dockerfile: RedisDockerfile
    env_file:
      - .docker-env
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  db-data:
    name: "fanfan-db-data"
    driver: local
  redis-data:
    name: "fanfan-redis-data"
    driver: local
