version: '3.8'
services:
  bot:
    container_name: 'fanfan-bot'
    build:
      context: .
      dockerfile: buildfiles/BotDockerfile
    env_file:
      - .env
    restart: unless-stopped
    stop_signal: SIGINT
    volumes:
      - bot-data:/media/bot-data
      - ./alembic.ini:/app/alembic.ini
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  db:
    container_name: 'fanfan-db'
    build:
      context: buildfiles
      dockerfile: DBDockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    container_name: 'fanfan-redis'
    build:
      context: buildfiles
      dockerfile: RedisDockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  bot-data:
    name: "fanfan-bot-data"
    driver: local
  db-data:
    name: "fanfan-db-data"
    driver: local
  redis-data:
    name: "fanfan-redis-data"
    driver: local
