version: '3.7'
services:
  bot:
    container_name: 'fanfan-bot'
    build:
      context: .
      dockerfile: buildfiles/Dockerfile
    env_file:
      - .env
    restart: always
    stop_signal: SIGINT
    volumes:
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    networks:
      - internal
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  db:
    container_name: 'fanfan-db'
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal
      - web
    ports:
      - "54320:5432"
  redis:
    container_name: 'fanfan-redis'
    build:
      context: buildfiles
      dockerfile: RedisDockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - internal
      - web
    ports:
      - "6379:6379"
  caddy:
    container_name: 'fanfan-webhook'
    build:
      context: buildfiles
      dockerfile: CaddyDockerfile
    env_file:
      - .env
    restart: always
    networks:
      - internal
      - web
    ports:
      - "80:80"
      - "443:443"
    profiles:
      - webhook

networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

volumes:
  db-data:
    name: "fanfan-db-data"
    driver: local
  redis-data:
    name: "fanfan-redis-data"
    driver: local
