services:
  bot:
    image: bot_image
    build:
      context: .
      dockerfile: buildfiles/BotDockerfile
    env_file:
      - .env
    restart: unless-stopped
    stop_signal: SIGINT
    volumes:
      - bot-data:/media/bot-data
      - ./alembic.ini:/app/alembic.ini
    ports:
      - $BOT_WEBHOOK_PORT:$BOT_WEBHOOK_PORT
    depends_on:
      - db
      - redis
  web:
    image: bot_image
    env_file:
      - .env
    restart: unless-stopped
    stop_signal: SIGINT
    volumes:
      - bot-data:/media/bot-data
    ports:
      - $WEB_PORT:$WEB_PORT
    depends_on:
      - db
      - redis
    command:
      [
        "python",
        "-m",
        "fanfan.main.web",
      ]
  worker:
    image: bot_image
    restart: always
    env_file:
      - .env
    volumes:
      - bot-data:/media/bot-data
    command:
      [
        "taskiq",
        "worker",
        "fanfan.infrastructure.scheduler:broker",
        "fanfan.infrastructure.scheduler.tasks",
      ]
  scheduler:
    image: bot_image
    depends_on:
      - bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - bot-data:/media/bot-data
    command:
      [
        "taskiq",
        "scheduler",
        "fanfan.infrastructure.scheduler:scheduler",
        "fanfan.infrastructure.scheduler.tasks",
      ]
  db:
    build:
      context: buildfiles
      dockerfile: DBDockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    build:
      context: buildfiles
      dockerfile: RedisDockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  bot-data:
    driver: local
  db-data:
    driver: local
  redis-data:
    driver: local
