version: '3.8'
services:
  bot:
    container_name: 'fanfan-bot'
    build:
      context: .
      dockerfile: buildfiles/BotDockerfile
    env_file:
      - .docker-env
    restart: unless-stopped
    stop_signal: SIGINT
    volumes:
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      - db
      - redis
  db:
    container_name: 'fanfan-db'
    build:
      context: buildfiles
      dockerfile: DBDockerfile
    restart: unless-stopped
    env_file:
      - .docker-env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  redis:
    container_name: 'fanfan-redis'
    build:
      context: buildfiles
      dockerfile: RedisDockerfile
    env_file:
      - .docker-env
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

volumes:
  db-data:
    name: "fanfan-db-data"
    driver: local
  redis-data:
    name: "fanfan-redis-data"
    driver: local
