version: '3.7'
services:
  bot:
    container_name: 'fanfan-bot'
    build:
      context: .
      dockerfile: buildfiles/Dockerfile
    env_file:
      - .env
    restart: always
    stop_signal: SIGINT
    depends_on:
      - db
  db:
    container_name: 'fanfan-db'
    image: postgres:15-alpine
    restart: on-failure
    env_file:
      - .env
    volumes:
      - /var/lib/docker/volumes/postgres/_data:/var/lib/postgresql/data
    ports:
      - "54320:5432"