[tool.poetry]
name = "fanfan-bot"
version = "0.1.0"
description = ""
authors = ["Arutemu64 <arutemu64@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.0.0"
aiogram-dialog = "^2.0.0"
alembic = "^1.12.0"
asyncpg = "^0.28.0"
environs = "^9.5.0"
jinja2 = "^3.1.2"
opencv-python-headless = "^4.8.0.74"
qrcode = "^7.4.2"
qreader = {version = "^3.7"}
redis = "^5.0.0"
sentry-sdk = "^1.30.0"
sqlalchemy = "^2.0.20"
torch = {version = "^2.0.1+cpu", source="torch-cpu"}
torchvision = {version = "^0.15.2+cpu", source = "torch-cpu"}

[tool.poetry.group.dev]
optional=true

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.5.1"
ruff = "^0.0.287"

[tool.ruff]
line-length = 88
select = ["E", "F", "I001"]
exclude = ["src/bot/ui/*"]
unfixable = ["F401", "E712"]

[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin"]

[[tool.mypy.overrides]]
module = [
  "src.db.*"
]
ignore_errors = true




[tool.poetry.group.scripts]
optional=true

[tool.poetry.group.scripts.dependencies]
openpyxl = "^3.1.2"
pandas = "^2.0.3"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
