[project]
name = "fanfan-bot"
version = "1.1.1"
authors = [
    { name = "Arutemu64", email = "arutemu64@outlook.com" },
]
description = "Festival bot"
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
    "adaptix>=3.0.0b8",
    "aiogram[fast]>=3.13.1",
    "aiogram-dialog>=2.2.0",
    "alembic>=1.13.3",
    "dataclass-rest>=0.4",
    "dishka>=1.3.0",
    "fastapi>=0.115.2",
    "fastapi-storages>=0.3.0",
    "faststream[cli,nats]",
    "itsdangerous>=2.2.0",
    "jinja2>=3.1.4",
    "numpy>=2.1.2",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "psycopg[binary]>=3.2.3",
    "pydantic>=2.9.2",
    "pydantic-settings>=2.5.2",
    "pyjwt>=2.9.0",
    "qrcode[pil]>=8.0",
    "redis>=5.1.1",
    "sentry-sdk[sqlalchemy]>=2.16.0",
    "sqladmin>=0.19.0",
    "sqlalchemy>=2.0.35",
    "sulguk>=0.8.0",
    "taskiq>=0.11.7",
    "taskiq-redis>=1.0.2",
    "uvicorn>=0.31.1",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.8",
    "uv-sort>=0.2.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["fanfan"]
