[tool.poetry]
name = "fanfan-bot"
version = "0.1.0"
description = ""
authors = ["Arutemu64 <arutemu64@outlook.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
aiogram = {version = "^3.2.0", extras = ["fast"]}
aiogram-dialog = "^2.1.0b3"
alembic = "^1.12.1"
alembic-postgresql-enum = "^0.4.0"
alembic-utils = "^0.8.2"
arq = "^0.25.0"
asyncpg = "^0.29.0"
fastapi = "^0.104.1"
itsdangerous = "^2.1.2"
jinja2 = "^3.1.3"
numpy = "^1.26.2"
openpyxl = "^3.1.2"
pandas = "^2.1.3"
pydantic-settings = "^2.1.0"
pyjwt = "^2.8.0"
qrcode = {version = "^7.4.2", extras = ["pil"]}
redis = "^5.0.1"
sentry-sdk = "^1.38.0"
sqladmin = "^0.16.0"
sqlalchemy = "^2.0.23"
uvicorn = "^0.24.0.post1"

[tool.poetry.group.dev]
optional=true

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.6.1"
ruff = "^0.1.1"

[tool.ruff]
line-length = 88
select = ["E", "F", "I001"]
exclude = ["src/bot/ui/*"]
unfixable = ["F401", "E712"]

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
