[tool.poetry]
name = "fanfan-bot"
version = "0.1.0"
description = ""
authors = ["Arutemu64 <arutemu64@outlook.com>"]
packages = [{include = "fanfan"}]

[tool.poetry.dependencies]
python = "^3.12"
aiogram = {version = "^3.3.0", extras = ["fast"]}
aiogram-dialog = "^2.1.0"
alembic = "^1.13.1"
arq = "^0.25.0"
asyncpg = "^0.29.0"
fastapi = "^0.109.1"
itsdangerous = "^2.1.2"
jinja2 = "^3.1.3"
numpy = "^1.26.3"
openpyxl = "^3.1.2"
pandas = "^2.2.0"
pydantic = "2.5.3"
pydantic-settings = "^2.1.0"
pyjwt = "^2.8.0"
qrcode = {version = "^7.4.2", extras = ["pil"]}
redis = "^5.0.1"
sentry-sdk = "^1.40.0"
sqladmin = "^0.16.0"
sqlalchemy = "^2.0.25"
uvicorn = "^0.27.0"

[tool.poetry.group.dev]
optional=true

[tool.poetry.group.dev.dependencies]
black = "^23.12.1"
mypy = "^1.8.0"
ruff = "^0.1.14"

[tool.ruff]
line-length = 88
select = ["E", "F", "I001"]
exclude = ["src/bot/ui/*"]
unfixable = ["F401", "E712"]

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
