[tool.poetry]
name = "fanfan-bot"
version = "0.1.0"
description = ""
authors = ["Arutemu64 <arutemu64@outlook.com>"]
packages = [{include = "fanfan"}]

[tool.poetry.dependencies]
python = "^3.12"
aiogram = {version = "^3.5.0", extras = ["fast"]}
aiogram-dialog = "^2.1.0"
alembic = "^1.13.1"
asyncpg = "^0.29.0"
dataclass-rest = "^0.4"
dishka = "^1.1.1"
fastapi = "^0.111.0"
fastapi-storages = "^0.3.0"
itsdangerous = "^2.2.0"
jinja2 = "^3.1.3"
numpy = "^1.26.4"
openpyxl = "^3.1.2"
orjson = "^3.10.3"
pandas = "^2.2.2"
pydantic = "^2.7.1"
pydantic-settings = "^2.2.1"
pyjwt = "^2.8.0"
qrcode = {version = "^7.4.2", extras = ["pil"]}
redis = "^5.0.4"
sentry-sdk = "^2.0.1"
sqladmin = "^0.16.1"
sqlalchemy = "^2.0.29"
sulguk = "^0.7.0"
taskiq = "^0.11.0"
taskiq-redis = "^0.5.5"
uvicorn = "^0.29.0"

[tool.poetry.group.dev]
optional=true

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
ruff = "^0.4.1"

[tool.ruff]
lint.select = ['E', 'F', 'W', 'A', 'PLC', 'PLE', 'PLW', 'I']

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
