[tool.poetry]
name = "fanfan-bot"
version = "0.1.0"
description = ""
authors = ["Arutemu64 <arutemu64@outlook.com>"]

[tool.poetry.dependencies]
python = "3.11.*"
aiogram = "^3.1.1"
aiogram-dialog = "^2.0.0"
alembic = "^1.12.0"
alembic-postgresql-enum = "^0.2.1"
alembic-utils = "^0.8.2"
arq = "^0.25.0"
asyncpg = "^0.28.0"
environs = "^9.5.0"
fastapi = "^0.103.2"
itsdangerous = "^2.1.2"
jinja2 = "^3.1.2"
numpy = "^1.26.0"
openpyxl = "^3.1.2"
pandas = "^2.0.3"
pyjwt = "^2.8.0"
qrcode = {version = "^7.4.2", extras = ["pil"]}
redis = "^5.0.1"
sentry-sdk = {version = "^1.32.0", extras = ["sqlalchemy", "redis"]}
sqladmin = "^0.15.2"
sqlalchemy = "^2.0.22"
uvicorn = "^0.23.2"
xlrd = "^2.0.1"

[tool.poetry.group.dev]
optional=true

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.6.1"
ruff = "^0.1.1"

[tool.ruff]
line-length = 88
select = ["E", "F", "I001"]
exclude = ["src/bot/ui/*"]
unfixable = ["F401", "E712"]

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
