[project]
name = "fanfan-bot"
version = "1.1.0"
authors = [
    { name = "Arutemu64", email = "arutemu64@outlook.com" },
]
description = "Festival bot"
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
    "adaptix>=3.0.0b8",
    "aiogram[fast]>=3.12.0",
    "aiogram-dialog>=2.2.0",
    "alembic>=1.13.2",
    "asyncpg>=0.29.0",
    "dataclass-rest>=0.4",
    "dishka>=1.3.0",
    "fastapi>=0.114.2",
    "fastapi-storages>=0.3.0",
    "itsdangerous>=2.2.0",
    "jinja2>=3.1.4",
    "numpy>=2.1.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.2",
    "pydantic>=2.8.2",
    "pydantic-settings>=2.5.2",
    "pyjwt>=2.9.0",
    "qrcode[pil]>=7.4.2",
    "redis>=5.0.8",
    "sentry-sdk>=2.14.0",
    "sqladmin>=0.19.0",
    "sqlalchemy>=2.0.34",
    "sulguk>=0.8.0",
    "taskiq>=0.11.7",
    "taskiq-redis>=1.0.0",
    "uvicorn>=0.30.6",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.5",
    "uv-sort>=0.2.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["fanfan"]
