[tool.poetry]
name = "fanfan-bot"
version = "0.1.0"
description = ""
authors = ["Arutemu64 <arutemu64@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiocache = "^0.12.1"
aiogram = "3.0b7"
aiogram-dialog = "^2.0.0b20"
alembic = "^1.11.1"
asyncpg = "^0.28.0"
opencv-python-headless = "^4.8.0.74"
pyngrok = "^6.0.0"
qreader = {version = "^2.13", extras = ["yolo7"]}
redis = "^4.6.0"
sentry-sdk = "^1.28.1"
sqlalchemy = "^2.0.19"
torch = {version = "^2.0.1+cpu", source="torch-cpu"}
torchvision = {version = "^0.15.2+cpu", source = "torch-cpu"}

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
flake8 = "^6.0.0"
isort = "^5.12.0"

[tool.poetry.group.dev]
optional=true

[tool.isort]
profile = "black"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
