"""init

Revision ID: 001
Revises: 
Create Date: 2023-06-23 19:02:28.115994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nominations',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('nomination_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('position'),
    sa.UniqueConstraint('position')
    )
    op.create_table('settings',
    sa.Column('voting_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('voting_enabled')
    )
    op.create_table('users',
    sa.Column('ticket_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ticket_id'),
    sa.UniqueConstraint('tg_id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_table('votes',
    sa.Column('vote_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('nomination_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('vote_id'),
    sa.UniqueConstraint('vote_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('schedule')
    op.drop_table('nominations')
    # ### end Alembic commands ###
