"""participant-title-index

Revision ID: 002
Revises: 001
Create Date: 2023-08-19 19:12:22.502346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_nominations_id'), 'nominations', ['id'])
    op.drop_constraint('uq_participants_title', 'participants', type_='unique')
    op.create_index(op.f('ix_participants_title'), 'participants', ['title'], unique=True)
    op.create_unique_constraint(op.f('uq_participants_id'), 'participants', ['id'])
    op.create_unique_constraint(op.f('uq_schedule_id'), 'schedule', ['id'])
    op.create_unique_constraint(op.f('uq_subscriptions_id'), 'subscriptions', ['id'])
    op.create_unique_constraint(op.f('uq_tickets_id'), 'tickets', ['id'])
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    op.create_unique_constraint(op.f('uq_votes_id'), 'votes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_votes_id'), 'votes', type_='unique')
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_tickets_id'), 'tickets', type_='unique')
    op.drop_constraint(op.f('uq_subscriptions_id'), 'subscriptions', type_='unique')
    op.drop_constraint(op.f('uq_schedule_id'), 'schedule', type_='unique')
    op.drop_constraint(op.f('uq_participants_id'), 'participants', type_='unique')
    op.drop_index(op.f('ix_participants_title'), table_name='participants')
    op.create_unique_constraint('uq_participants_title', 'participants', ['title'])
    op.drop_constraint(op.f('uq_nominations_id'), 'nominations', type_='unique')
    # ### end Alembic commands ###
