"""proper_cascade_deletes

Revision ID: 003
Revises: 002
Create Date: 2023-08-13 16:41:48.398808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscriptions_user_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tickets_issued_by_fkey', 'tickets', type_='foreignkey')
    op.drop_constraint('tickets_used_by_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['issued_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tickets', 'users', ['used_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint('votes_user_id_fkey', 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key('votes_user_id_fkey', 'votes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_used_by_fkey', 'tickets', 'users', ['used_by'], ['id'])
    op.create_foreign_key('tickets_issued_by_fkey', 'tickets', 'users', ['issued_by'], ['id'])
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key('subscriptions_user_id_fkey', 'subscriptions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
