"""settings

Revision ID: 006
Revises: 005
Create Date: 2023-09-04 21:21:07.347317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('voting_enabled', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('announcement_timestamp', sa.Float(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('id', name=op.f('uq_settings_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
