"""helper_can_edit_schedule

Revision ID: 003
Revises: 002
Create Date: 2024-12-14 22:04:21.829970

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "003"
down_revision = "002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_permissions",
        sa.Column(
            "helper_can_edit_schedule",
            sa.Boolean(),
            server_default="False",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_permissions", "helper_can_edit_schedule")
    # ### end Alembic commands ###
