"""can_create_tickets

Revision ID: 010
Revises: 009
Create Date: 2025-04-12 16:03:46.843731

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "010"
down_revision = "009"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_permissions",
        sa.Column(
            "can_edit_schedule", sa.Boolean(), server_default="False", nullable=False
        ),
    )
    op.add_column(
        "user_permissions",
        sa.Column(
            "can_create_tickets", sa.Boolean(), server_default="False", nullable=False
        ),
    )
    op.drop_column("user_permissions", "helper_can_edit_schedule")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_permissions",
        sa.Column(
            "helper_can_edit_schedule",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("user_permissions", "can_create_tickets")
    op.drop_column("user_permissions", "can_edit_schedule")
    # ### end Alembic commands ###
