"""feedback_remove_agreement.

Revision ID: 013
Revises: 012
Create Date: 2024-04-28 13:11:56.017263

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "013"
down_revision = "012"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feedback", "contact_agreement")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feedback",
        sa.Column(
            "contact_agreement",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
