"""schedule_event_duration

Revision ID: 014
Revises: 013
Create Date: 2025-05-11 20:08:39.410616

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "014"
down_revision = "013"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule",
        sa.Column("duration", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "duration")
    # ### end Alembic commands ###
