"""achievement_secret_id_non_uuid.

Revision ID: 015
Revises: 014
Create Date: 2024-07-20 20:05:55.318565

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "015"
down_revision = "014"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE achievements "
        "ALTER COLUMN secret_id TYPE varchar USING (secret_id::varchar)"
    )
    op.alter_column(
        "achievements", "secret_id", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE achievements "
        "ALTER COLUMN secret_id TYPE uuid USING (secret_id::uuid)"
    )
    op.alter_column(
        "achievements", "secret_id", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
