"""remove-activity-subtext

Revision ID: 018
Revises: 017
Create Date: 2024-10-20 13:21:54.052975

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "018"
down_revision = "017"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activities", "subtext")
    op.create_unique_constraint(op.f("uq_nominations_title"), "nominations", ["title"])
    op.create_index(
        op.f("ix_participants_title"), "participants", ["title"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_participants_title"), table_name="participants")
    op.drop_constraint(op.f("uq_nominations_title"), "nominations", type_="unique")
    op.add_column(
        "activities",
        sa.Column("subtext", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
