"""remove-activity-subtext

Revision ID: 018
Revises: 017
Create Date: 2024-10-20 13:21:54.052975

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "018"
down_revision = "017"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activities", "subtext")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities",
        sa.Column("subtext", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
