"""feedback_v2

Revision ID: 020
Revises: 019
Create Date: 2024-11-03 11:36:21.157413

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "020"
down_revision = "019"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("feedback", sa.Column("mailing_id", sa.String(), nullable=True))
    op.add_column(
        "feedback", sa.Column("processed_by_id", sa.BigInteger(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_feedback_processed_by_id_users"),
        "feedback",
        "users",
        ["processed_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("feedback", "asap")
    op.drop_constraint(
        "fk_schedule_participant_id_participants", "schedule", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_schedule_participant_id_participants"),
        "schedule",
        "participants",
        ["participant_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("settings", "asap_feedback_enabled")
    op.add_column(
        "user_settings",
        sa.Column(
            "org_receive_feedback_notifications",
            sa.Boolean(),
            server_default="True",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "org_receive_feedback_notifications")
    op.add_column(
        "settings",
        sa.Column(
            "asap_feedback_enabled",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("fk_schedule_participant_id_participants"), "schedule", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_schedule_participant_id_participants",
        "schedule",
        "participants",
        ["participant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "feedback", sa.Column("asap", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(
        op.f("fk_feedback_processed_by_id_users"), "feedback", type_="foreignkey"
    )
    op.drop_column("feedback", "processed_by_id")
    op.drop_column("feedback", "mailing_id")
    # ### end Alembic commands ###
