"""global_notifications_enabled_by_default.

Revision ID: 005
Revises: 004
Create Date: 2024-04-07 02:01:46.016405

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "005"
down_revision = "004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "receive_all_announcements", server_default="True")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "receive_all_announcements", server_default="False")
    # ### end Alembic commands ###
