"""user_settings.

Revision ID: 007
Revises: 006
Create Date: 2024-04-13 16:24:07.494981

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "007"
down_revision = "006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("items_per_page", sa.Integer(), server_default="5", nullable=False),
        sa.Column(
            "receive_all_announcements",
            sa.Boolean(),
            server_default="True",
            nullable=False,
        ),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_settings")),
    )
    op.alter_column("achievements", "secret_id", existing_type=sa.UUID(), nullable=True)
    op.execute(
        "INSERT INTO user_settings (user_id, receive_all_announcements, "
        "items_per_page) "
        "SELECT id, receive_all_announcements, items_per_page "
        "FROM users",
    )
    op.drop_column("users", "receive_all_announcements")
    op.drop_column("users", "items_per_page")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "items_per_page",
            sa.INTEGER(),
            server_default=sa.text("5"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "receive_all_announcements",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "achievements",
        "secret_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.execute(
        "UPDATE users "
        "SET items_per_page = user_settings.items_per_page, "
        "receive_all_announcements = user_settings.receive_all_announcements "
        "FROM user_settings "
        "WHERE user_settings.user_id = users.id",
    )
    op.drop_table("user_settings")
    # ### end Alembic commands ###
