"""feedback_nullable

Revision ID: 009
Revises: 008
Create Date: 2024-04-14 13:27:51.113218

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "009"
down_revision = "008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("feedback", "user_id", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("feedback", "user_id", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###
