"""feedback_asap

Revision ID: 010
Revises: 009
Create Date: 2024-04-14 21:37:33.553835

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "010"
down_revision = "009"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings",
        sa.Column(
            "asap_feedback_enabled", sa.Boolean(), server_default="True", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "asap_feedback_enabled")
    # ### end Alembic commands ###
