"""participants_scoped_id.

Revision ID: 014
Revises: 013
Create Date: 2024-05-24 20:07:13.788916

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "014"
down_revision = "013"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE participants_scoped_id_seq")
    op.add_column(
        "participants",
        sa.Column(
            "scoped_id",
            sa.Integer(),
            server_default=sa.text("nextval('participants_scoped_id_seq')"),
            nullable=False,
        ),
    )
    op.drop_constraint("uq_participants_order", "participants", type_="unique")
    op.create_unique_constraint(
        op.f("uq_participants_nomination_id"),
        "participants",
        ["nomination_id", "scoped_id"],
    )
    op.drop_column("participants", "order")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participants",
        sa.Column(
            "order",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("nextval('participants_order_seq'::regclass)"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("uq_participants_nomination_id"),
        "participants",
        type_="unique",
    )
    op.create_unique_constraint("uq_participants_order", "participants", ["order"])
    op.drop_column("participants", "scoped_id")
    op.execute("DROP SEQUENCE participants_scoped_id_seq")
    # ### end Alembic commands ###
