"""quest

Revision ID: 017
Revises: 016
Create Date: 2024-09-18 19:49:03.920846

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "017"
down_revision = "016"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quest_registrations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_quest_registrations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quest_registrations")),
        sa.UniqueConstraint("user_id", name=op.f("uq_quest_registrations_user_id")),
    )
    op.add_column(
        "settings",
        sa.Column(
            "quest_registration_enabled",
            sa.Boolean(),
            server_default="False",
            nullable=False,
        ),
    )
    op.add_column(
        "settings",
        sa.Column(
            "quest_registrations_limit",
            sa.Integer(),
            server_default="10",
            nullable=False,
        ),
    )
    op.add_column(
        "users", sa.Column("points", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "points")
    op.drop_column("settings", "quest_registrations_limit")
    op.drop_column("settings", "quest_registration_enabled")
    op.drop_table("quest_registrations")
    # ### end Alembic commands ###
