timezone = "Europe/Moscow"
media_root = "/media/bot-data"

[bot]
token = ""
mode = "polling"

[bot.webhook]
host = "bot"
port = 8080

[web]
host = "web"
port = 8081
base_url = 'https://example.com/'
secret_key = ""

[db]
host = "db"
port = 5432
user = "fanfan"
password = ""
name = "fanfan"
echo = false

[redis]
host = "redis"
port = 6379
password = ""
database = "0"

[nats]
host = "nats"
port = 4222
user = "fanfan"
password = ""

[timepad]
client_id = ""
event_id = 0
secret = ""

[cosplay2]
subdomain = ""
login = ""
password = ""

[debug]
enabled = true
logging_level = 20
sentry_enabled = true
sentry_dsn = ""
otlp_endpoint='http://tempo:4317/'
json_logs = false